DGSN_Math: PositionsList Class Reference
PositionsList Class Reference
Class which stores list of positions.
#include <Def.h>
Public Member Functions
PositionsList ()
Default constructor.
PositionsList (Position aPosition)
Constructor.
void addPosition (Position aPosition)
Adding position to the list.
void addPosition (std::vector< double > aPosVec)
Adding position using its coordinates.
void addPositions (std::vector< Position > aPositions)
Adding vector of positions.
Position getPosition (int aIndex) const
Getting position with given index.
void addPositions (PositionsList aList)
Adding on the end of the PositionsList another PositionsList.
int size () const
Getting number of stored positions.
double getX (int aIndex)
Getting coordinate x of given position.
double getY (int aIndex)
Getting coordinate y of given position.
double getZ (int aIndex)
Getting coordinate z of given position.
double getR (int aIndex)
Getting distance between vehicle and ground station.
void printPositions ()
Printing data of all positions on the list.
void printAveragePosition ()
Printing average of all stored positions.
Detailed Description
Class which stores list of positions.
Definition at line 163 of file Def.h.
Constructor & Destructor Documentation
PositionsList::PositionsList () inline
Default constructor.
Definition at line 169 of file Def.h.
PositionsList::PositionsList (Position aPosition) inline
Constructor.
Parameters
aPosition first position which will be on the list
Definition at line 175 of file Def.h.
Member Function Documentation
void PositionsList::addPosition (Position aPosition) inline
Adding position to the list.
Parameters
aPosition position which is added
Definition at line 181 of file Def.h.
void PositionsList::addPosition (std::vector< double > aPosVec) inline
Adding position using its coordinates.
Parameters
aPosVec vector of coordinates.
Definition at line 187 of file Def.h.
void PositionsList::addPositions (std::vector< Position > aPositions) inline
Adding vector of positions.
Parameters
aPosVec vector of positions
Definition at line 197 of file Def.h.
Position PositionsList::getPosition (int aIndex) const inline
Getting position with given index.
Parameters
aIndex index of position which is returned
Definition at line 210 of file Def.h.
Referenced by addPositions().
void PositionsList::addPositions (PositionsList aList) inline
Adding on the end of the PositionsList another PositionsList.
Parameters
aList PositionList which is added
Definition at line 216 of file Def.h.
References getPosition(), and size().
int PositionsList::size () const inline
Getting number of stored positions.
Definition at line 227 of file Def.h.
Referenced by addPositions().
double PositionsList::getX (int aIndex) inline
Getting coordinate x of given position.
Parameters
aIndex index of position which coordinate is returned
Definition at line 233 of file Def.h.
double PositionsList::getY (int aIndex) inline
Getting coordinate y of given position.
Parameters
aIndex index of position which coordinate is returned
Definition at line 239 of file Def.h.
double PositionsList::getZ (int aIndex) inline
Getting coordinate z of given position.
Parameters
aIndex index of position which coordinate is returned
Definition at line 245 of file Def.h.
double PositionsList::getR (int aIndex) inline
Getting distance between vehicle and ground station.
Parameters
aIndex index of position
Definition at line 251 of file Def.h.
void PositionsList::printPositions () inline
Printing data of all positions on the list.
Definition at line 256 of file Def.h.
void PositionsList::printAveragePosition () inline
Printing average of all stored positions.
Definition at line 269 of file Def.h.
The documentation for this class was generated from the following file:
/home/marta/devel/DGSN/dgsn/src/Def.h