DGSN_Math: /home/marta/devel/DGSN/dgsn/src/Combinations.h File Reference
Combinations.h File Reference
#include <iostream>
#include <stdint.h>
#include <vector>
Functions
uint64_t initialBitCombination (int n, int k)
initialization of selected ground stations
uint64_t nextBitCombination (uint64_t currentBitCombination)
calculation of next combination of bits equal to 1 for given number algorithm: http://www-graphics.stanford.edu/~seander/bithacks.html#NextBitPermutation t = v | (v - 1); // t gets v's least significant 0 bits set to 1 Next set to 1 the most significant bit to change, set to 0 the least significant ones, and add the necessary 1 bits.
std::vector< std::vector< int > > getStationsCombinations (int n, int k)
generating list of ground stations
Function Documentation
uint64_t initialBitCombination (int n, int k)
initialization of selected ground stations
Parameters
n a number of all ground station
k a number of selected ground station
Returns
number with n-k bits '0' on the beginning and k bits '1'
Definition at line 10 of file Combinations.h.
Referenced by getStationsCombinations().
uint64_t nextBitCombination (uint64_t currentBitCombination)
calculation of next combination of bits equal to 1 for given number algorithm: http://www-graphics.stanford.edu/~seander/bithacks.html#NextBitPermutation t = v | (v - 1); // t gets v's least significant 0 bits set to 1 Next set to 1 the most significant bit to change, set to 0 the least significant ones, and add the necessary 1 bits.
Parameters
currentBitCombination a number of which bits equal to '1' represent selected ground stations
Returns
next combination of bits equal to 1
Definition at line 30 of file Combinations.h.
Referenced by getStationsCombinations().
std::vector< std::vector< int > > getStationsCombinations (int n, int k)
generating list of ground stations
Parameters
n number of all ground station
k number of selected ground station
Returns
vector of vectors containing numbers of selected ground stations
Definition at line 45 of file Combinations.h.
References initialBitCombination(), and nextBitCombination().